[project]
name = "clinic-demo"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "psycopg2-binary>=2.9.13",
    "pwdlib[argon2]>=0.3.1",
    "pyjwt>=2.14.0",
    "sqlmodel>=0.0.42",
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
